[package]
name = "speedwagon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
enum-primitive-derive = "0.2.2"
num-traits = "0.2.15"
